my_string = input('какое у тебя хобби? ')
print('в предложении',my_string,len(my_string),'букв')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string [0])
print(my_string [-1])